name: container
on:
  push:
    branches: [master]
    paths:
    - 'container/**'
defaults:
  run:
    working-directory: container
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm run build